targetSystem: "linux"
datadog:
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  site: datadoghq.com
  apm:
    portEnabled: true
  kubelet:
    tlsVerify: false
  logs:
    enabled: true
    containerCollectAll: true
# agents:
  # image:
  #   tag: 7.41.1
    # enabled: true
  # apm_config:
  #   enabled: true
  # datadog:
  #   apmEnabled: true 


