apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-sample-app
spec:
  selector:
    matchLabels:
      app: docker-sample-app
  template:
    metadata:
      labels:
        app: docker-sample-app
    spec:
      imagePullSecrets:
        - name: ecr-secret
      hostNetwork: true
      containers:
        - name: docker-sample-app
          image: 167855287371.dkr.ecr.ap-northeast-1.amazonaws.com/sre-onboarding-shinta-datadog:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
