apiVersion: v1
kind: Service
metadata:
  name: docker-sample-app
spec:
  type: LoadBalancer
  selector:
    app: docker-sample-app
  clusterIP: 127.0.0.1
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30601
